# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/ecspresso/main.go
    binary: ecspresso
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-{{ .Env.NIGHTLY_VERSION }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
