inputs:
  version:
    description: "A version to install ecspresso"
    default: latest
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: /tmp
      run: |
        set -e
        VERSION="${{ inputs.version }}"
        if [ "${VERSION}" = "latest" ]; then
          DOWNLOAD_URL=$(curl -sS https://api.github.com/repos/kayac/ecspresso/releases | jq -r '[.[]|select(.tag_name > "v2.0")|select(.prerelease==false)][0].assets[].browser_download_url|select(match("linux.amd64."))')
        else
          DOWNLOAD_URL=$(curl -sS https://api.github.com/repos/kayac/ecspresso/releases/tags/${VERSION}|jq -r '.assets[].browser_download_url|select(match("linux.amd64."))')
        fi
        cd /tmp
        curl -sfLO ${DOWNLOAD_URL}
        if [[ "${DOWNLOAD_URL}" =~ \.tar\.gz$ ]]; then
          FILENAME=$(basename $DOWNLOAD_URL .tar.gz)
          tar xzvf ${FILENAME}.tar.gz
          sudo install ecspresso /usr/local/bin/ecspresso
        elif [[ "${DOWNLOAD_URL}" =~ \.zip$ ]]; then
          FILENAME=$(basename $DOWNLOAD_URL .zip)
          unzip ${FILENAME}.zip
          sudo install ${FILENAME} /usr/local/bin/ecspresso
        fi
