name: test action
on:
  push:
    branches:
      - v2
      - v2-action-testing
  workflow_dispatch:

jobs:
  install_legacy:
    strategy:
      matrix:
        runner:
          - ubuntu-22.04
    name: test action
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - uses: kayac/ecspresso@v0
        with:
          version: v1.5.0
      - run: |
          ecspresso version 2>&1 | fgrep v1.5.0
      - uses: kayac/ecspresso@v1
        with:
          version: v1.6.0
      - run: |
          ecspresso version 2>&1 | fgrep v1.6.0
      - uses: kayac/ecspresso@v1
        with:
          version: latest
      - run: |
          ecspresso version 2>&1 | fgrep v1.7.
      - uses: kayac/ecspresso@v2
        with:
          version: latest
      - run: |
          ecspresso version 2>&1 | fgrep v2.
      - uses: kayac/ecspresso@v2
        with:
          version: v1.7.14
      - run: |
          ecspresso version 2>&1 | fgrep v1.7.14
      - uses: kayac/ecspresso@v2
        with:
          version-file: tests/.ecspresso-version
      - run: |
          ecspresso version 2>&1 | fgrep v2.0.0

      - run: |
          rm -f /usr/local/bin/ecspresso

      - uses: kayac/ecspresso@v2-action-testing
        with:
          version: latest
      - run: |
          ecspresso version 2>&1 | fgrep v2.
      - uses: kayac/ecspresso@v2-action-testing
        with:
          version: v2.0.4
      - run: |
          ecspresso version 2>&1 | fgrep v2.0.4

  install_v2:
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    name: test action
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - uses: kayac/ecspresso@v2-action-testing
        with:
          version: latest
      - run: |
          ecspresso version 2>&1 | fgrep v2.
      - uses: kayac/ecspresso@v2-action-testing
        with:
          version: v2.0.4
      - run: |
          ecspresso version 2>&1 | fgrep v2.0.4
      - uses: kayac/ecspresso@v2-action-testing
        with:
          version-file: tests/.ecspresso-version
      - run: |
          ecspresso version 2>&1 | fgrep v2.0.0
      - uses: kayac/ecspresso@v2
        with:
          version: v2.3.3
      - run: |
          ecspresso version 2>&1 | fgrep v2.3.3
      - uses: kayac/ecspresso@v2-action-testing
        with:
          version: latest
          args: "render config --jsonnet"
        env:
          AWS_REGION: ap-northeast-1
          ECSPRESSO_LOG_FORMAT: json
          ECSPRESSO_CONFIG: tests/ecspresso.yml
