name: Nightly release
on:
  schedule:
    - cron: "10 0 * * *"
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to build from"
        default: "v2"
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v5
        with:
          go-version: "1.25"

      - name: Check out code into the Go module directory
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0 # it is required for the changelog to work correctly.

      - name: Set env
        run: |
          git fetch --prune --tags
          full=$(git describe --abbrev --tags --always)
          version=$(echo "$full" | cut -d- -f1)
          commit=$(git log -1 --format="%h")
          echo "NIGHTLY_VERSION=${version}-nightly-${commit}" >> $GITHUB_ENV

      - name: Check for same revision exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set +e
          gh release list | grep "${{ env.NIGHTLY_VERSION }}"
          if [ $? -eq 0 ]; then
            echo "${{ env.NIGHTLY_VERSION }} already exists"
          else
            echo "DO_RELEASE=true" >> $GITHUB_ENV
            git tag "${{ env.NIGHTLY_VERSION }}"
          fi

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ env.DO_RELEASE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Docker Login
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and Push Docker Image
        run: |
          make image-push
        env:
          IMAGE_VERSION: ${{ env.NIGHTLY_VERSION }}
        if: ${{ env.DO_RELEASE }}
