name: Nightly release
on:
  schedule:
    - cron: "10 0 * * *"
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: "1.24"

      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: v2
          fetch-depth: 0 # it is required for the changelog to work correctly.

      - name: Set env
        run: |
          git fetch --prune --tags
          full=$(git describe --abbrev --tags --always)
          version=$(echo "$full" | cut -d- -f1)
          commit=$(git log -1 --format="%h")
          echo "NIGHTLY_VERSION=${version}-nightly-${commit}" >> $GITHUB_ENV

      - name: Check for same revision exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set +e
          gh release list | grep "${{ env.NIGHTLY_VERSION }}"
          if [ $? -eq 0 ]; then
            echo "${{ env.NIGHTLY_VERSION }} already exists"
          else
            echo "DO_RELEASE=true" >> $GITHUB_ENV
            git tag "${{ env.NIGHTLY_VERSION }}"
          fi

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ env.DO_RELEASE }}
