name: tagpr and release
on:
  push:
    branches: ["v2"]
  workflow_dispatch:
    inputs:
      tag:
        description: "release tag"
        required: false
        type: string

permissions:
  pull-requests: write
  packages: write
  contents: write
  actions: write
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
        with:
          ref: ${{ inputs.tag || github.ref }}
      - name: Get current branch
        run: |
          git checkout v2
          git symbolic-ref --short HEAD
      - uses: Songmu/tagpr@9d0f650553240dab1fa907eca27e3fd5b586e538 # v1.18.1
        id: tagpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'workflow_dispatch' }} # skip on workflow_dispatch
      # after tagpr adds a release tag, or workflow_dispatch, release it
      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: "1.26"
        if: ${{ steps.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch' }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@1a80836c5c9d9e5755a25cb59ec6f45a3b5f41a8 # v7
        with:
          version: "~> v2"
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
        if: ${{ steps.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        if: ${{ steps.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch' }}

      - name: Docker Login
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
        if: ${{ steps.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch' }}

      - name: Build and Push Docker Image
        run: |
          make image-push
        env:
          IMAGE_VERSION: ${{ steps.tagpr.outputs.tag || github.event.inputs.tag || 'latest' }}
        if: ${{ steps.tagpr.outputs.tag != '' || github.event_name == 'workflow_dispatch' }}
