name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.24"
          - "1.25"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5

      - name: Build & Test
        run: |
          make clean
          make test
          make install
