name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.25"
          - "1.26"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v6
        with:
          go-version: ${{ matrix.go }}

      - name: Build & Test
        run: |
          make clean
          make test
          make install
